apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-app
spec:
  ingressClassName: traefik
  rules:
    - host: app.lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot-app
                port:
                  name: http
